export const ourProductArray = [
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "Breed Dry Dog Food",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: false,
  },
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: false
  }, 
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: false
  }, 
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: false,
  }, 
  {
    discountBtn: true,
    discountPrice: "New",
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: true,
    color1: "bg-black",
    color2: "red",
  },
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: true,
    color1: "bg-black",    
    color2: "red",
  },
  {
    discountBtn: true,
    discountPrice: "New",
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: true,
    color1: "bg-black",    
    color2: "red",
  },
  {
    discountBtn: false,
    discountPrice: 40,
    trashIcon: false,
    heartIcon: true,
    eyeIcon: true,
    src: "/card1.png",
    Heading: "CANON EOS DSLR Camera",
    price: 100,
    star: 3,
    reviews: 35,
    colorDiv: true,
    color1: "bg-black",
    color2: "orange",
  }
]